### PR TITLE
add tests, update readme

### PR DESCRIPTION
**Pull request by garbados**
This patch adds a basic test suite using dispatch:mocha, and updates the readme to reflect (among other things) testing instructions.

This patch is WIP while the test suite grows. This patch also includes some dependency changes.

### CODE REVIEW

**Comment by garbados** [comment]
BTW: Moved all those TODOs to a file called TODO

**Comment by garbados** [comment]
App tests currently don't pass a smoke test, producing this error:

```bash
☭ garbados@deus:~/code/agora-meteor
↳ meteor test --once --full-app --driver-package dispatch:mocha && echo 'hello'
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
W20170908-20:34:54.360(-7)? (STDERR) /home/garbados/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170908-20:34:54.399(-7)? (STDERR) 						throw(ex);
W20170908-20:34:54.400(-7)? (STDERR) 						^
W20170908-20:34:54.401(-7)? (STDERR) 
W20170908-20:34:54.402(-7)? (STDERR) TypeError: Cannot read property 'before' of undefined
W20170908-20:34:54.402(-7)? (STDERR)     at meteorInstall.server.users.js (server/users.js:38:1)
W20170908-20:34:54.403(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170908-20:34:54.404(-7)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170908-20:34:54.405(-7)? (STDERR)     at routes.js:64:1
W20170908-20:34:54.405(-7)? (STDERR)     at /tmp/meteor-test-run1ktcd0w/.meteor/local/build/programs/server/boot.js:338:34
W20170908-20:34:54.406(-7)? (STDERR)     at Array.forEach (native)
W20170908-20:34:54.406(-7)? (STDERR)     at Function._.each._.forEach (/home/garbados/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170908-20:34:54.407(-7)? (STDERR)     at /tmp/meteor-test-run1ktcd0w/.meteor/local/build/programs/server/boot.js:158:5
W20170908-20:34:54.407(-7)? (STDERR)     at /tmp/meteor-test-run1ktcd0w/.meteor/local/build/programs/server/boot.js:387:5
W20170908-20:34:54.408(-7)? (STDERR)     at Function.run (/tmp/meteor-test-run1ktcd0w/.meteor/local/build/programs/server/profile.js:510:12)
=> Started your app.

=> App running at: http://localhost:3000/
```

That `&& echo 'hello'` bit is just to show that the command is erroring out, despite reporting  that the app had been started or was being served.

I haven't figured out the problem yet, so I just commented it from travis tests.

**Comment by garbados** [comment]
App tests currently don't pass a smoke test, producing this error:

```bash
☭ garbados@deus:~/code/agora-meteor
↳ meteor test --once --full-app --driver-package dispatch:mocha && echo 'hello'
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
W20170908-20:34:54.360(-7)? (STDERR) /home/garbados/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170908-20:34:54.399(-7)? (STDERR) 						throw(ex);
W20170908-20:34:54.400(-7)? (STDERR) 						^
W20170908-20:34:54.401(-7)? (STDERR) 
W20170908-20:34:54.402(-7)? (STDERR) TypeError: Cannot read property 'before' of undefined
W20170908-20:34:54.402(-7)? (STDERR)     at meteorInstall.server.users.js (server/users.js:38:1)
W20170908-20:34:54.403(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170908-20:34:54.404(-7)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170908-20:34:54.405(-7)? (STDERR)     at routes.js:64:1
W20170908-20:34:54.405(-7)? (STDERR)     at /tmp/meteor-test-run1ktcd0w/.meteor/local/build/programs/server/boot.js:338:34
W20170908-20:34:54.406(-7)? (STDERR)     at Array.forEach (native)
W20170908-20:34:54.406(-7)? (STDERR)     at Function._.each._.forEach (/home/garbados/.meteor/packages/meteor-tool/.1.5.2.ecibw9++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20170908-20:34:54.407(-7)? (STDERR)     at /tmp/meteor-test-run1ktcd0w/.meteor/local/build/programs/server/boot.js:158:5
W20170908-20:34:54.407(-7)? (STDERR)     at /tmp/meteor-test-run1ktcd0w/.meteor/local/build/programs/server/boot.js:387:5
W20170908-20:34:54.408(-7)? (STDERR)     at Function.run (/tmp/meteor-test-run1ktcd0w/.meteor/local/build/programs/server/profile.js:510:12)
=> Started your app.

=> App running at: http://localhost:3000/
```

That `&& echo 'hello'` bit is just to show that the command is erroring out, despite reporting  that the app had been started or was being served.

I haven't figured out the problem yet, so I just commented it from travis tests.

**Comment by Angular-Angel** [comment]
That looks like the kind of problem that arises when the collections2 package isn't being loaded right. ;/

**Comment by garbados** [comment]
Hmm. aldeed:collection2 is in `meteor list` so I'm not sure why it would fail while running app tests. I'll look into it more over time.

**Pull request merged**
